### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by jinhong-** [guzmonne/dynamodb-graph#1]
Nice work there. Just a couple of suggestions:
- You should probably link your npm package to the repository. It took me some googling to get here :)
- I am just wondering what's the performance like? Is it comparable to other alternatives?

**Comment by guzmonne** [comment]
I'll definitely add a link for the NPM package, I am sorry I didn't think about it first.

Regarding performance, I really don't know of what alternatives you are talking about. I have been using it on some of my projects, and it is working fine. Maybe you can point me to these alternatives so I can check them out.

At the moment I am working on adapting the API to make it look more like the Cypher Query language used by Neo4j.

Thank you very much for your suggestions.
